### ISSUE TITLE
Messenger API #1200 OAuthExeption.

### ISSUE THREAD

**Issue by KhaldiAmer** [Yoctol/messaging-apis#237]
The error is `Temporary send message failure. Please try again later.`
How can I fix this?

**Comment by tw0517tw** [comment]
Facebook Messenger Platform is down. We have to wait Facebook fix this.

https://developers.facebook.com/status/issues/109151043206199/

**Comment by KhaldiAmer** [comment]
Thank you! :clap:

**Comment by tw0517tw** [comment]
Facebook says it's been fixed, closing.
