### ISSUE TITLE
#Slack API - Invite new users by api

### ISSUE THREAD

**Issue by flavianohonorato** [Yoctol/messaging-apis#277]
Is there any way to add a user via api? without having to send email as it is done today ?. Who knows just providing email and password, and may I already add it to a specific channel?

**Comment by tw0517tw** [comment]
Hi @flavianohonorato ,

It's not possible as Slack didn't provide any API to do that. You can check their [API List](https://api.slack.com/methods).
You can also try to ask Slack's customer service for further details.
