### ISSUE TITLE
 images url failed at the readme of `messaging-apis/packages/messaging-api-line/ `

### ISSUE THREAD

**Issue by tigercosmos** [Yoctol/messaging-apis#279]

**Comment by kpman** [comment]
Thanks for reporting.
We will fix it soon.

I think we should store these photos in the image-host service (like imgur) rather than link back to the official website url.

**Comment by tw0517tw** [comment]
I think we should use the official website urls as they are *official*, so we need to keep an eye on whether official images has changed.

Also GitHub seems to keep a cache version of the outside image, I'm not sure how this will affect the image links.

**Comment by tigercosmos** [comment]
> I think we should use the official website urls as they are official, so we need to keep an eye on whether official images has changed.

Let CI checks for it maybe is a good way(?)

I thought we should let the current version works anytime.

**Comment by chentsulin** [comment]
We can try using [awesome_bot](https://github.com/dkhamsing/awesome_bot) to catch those issue.

**Comment by chentsulin** [comment]
Broken links fixed.
