### ISSUE TITLE
SendFile attach wrong form data key

### ISSUE THREAD

**Issue by kpman** [Yoctol/messaging-apis#333]
Due to the [official docs](https://developers.facebook.com/docs/messenger-platform/send-messages#sending_attachments), the send API with file accepted the following keys:
```
- recipient: A JSON object identifying the message recipient.
- message: A JSON object describing the message. Includes the asset type, and a payload. The payload is either empty, or sets the is_reusable property.
- filedata:The location of the asset on your file system and MIME type.
```

But the client `sendFile` seems to append the wrong keys.
https://github.com/Yoctol/messaging-apis/blob/67ffb224cb06ac9e5cf8629895bf11078dc992ac/packages/messaging-api-messenger/src/MessengerClient.js#L658-L669

**Comment by chentsulin** [comment]
`message` and `filedata` already attached on formdata before passing into this function..

**Comment by kpman** [comment]
Got it.
