### ISSUE TITLE
[Error Handling] Avoid access response data when response not exists

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/messaging-apis#336]
We should have better error message in this `ECONNRESET` case. 

https://github.com/Yoctol/bottender/issues/246

**Comment by tw0517tw** [comment]
Maybe we could do `_.get` with the data needed and fallback `msg` to original `error.message` in `handleError` of the packages.

Also need to update `axios-error`.
https://github.com/Yoctol/messaging-apis/blob/v0.6.16/packages/axios-error/src/index.js#L33
