### ISSUE TITLE
How can get access token? Access Token for App or Page or User?

### ISSUE THREAD

**Issue by ptit9x** [Yoctol/messaging-apis#337]
Hi there,
I tried your package for my project to send Text message. But I got an issue about token. I don't know why. any guys can help me it? This is a response:
`{
  message: 'An active access token must be used to query information about the current user.',
  type: 'OAuthException',
  code: 2500,
  fbtrace_id: 'AhX2W3PhsHH'
}`

this is my code:
`
import FBMessenger from 'fb-messenger';

const sendMessage = async (req, res, next) => {
  const client = new FBMessenger('{ACCESS_TOKEN}');

  client.sendTextMessage(
    '{my_facebook_id}',
    'Hello', function (err, body) {
      if (err) return console.error(err)
      console.log(body)
    });
};
export { sendMessage };
`

**Comment by chentsulin** [comment]
Hi @ptit9x, I'm afraid that we are not the right place to answer questions about `fb-messenger` package, you should go to https://github.com/DiegoRBaquero/node-fb-messenger for more details.

To get a facebook page token, you can visit below url (you must replace `<your_fb_app_id>` to your real app id).
`https://developers.facebook.com/apps/<your_fb_app_id>/messenger/settings/`

**Comment by ptit9x** [comment]
Hi @chentsulin , Thanks for your response. So as i understand, ACCESS_TOKEN input should be Page Token? not App or User Token?

**Comment by chentsulin** [comment]
yes, it should be a page token
