### ISSUE TITLE
Cannot specify dependencies between requests in batch messages

### ISSUE THREAD

**Issue by ayoisaiah** [Yoctol/messaging-apis#342]
Sometimes it is useful to specify dependencies between requests in the batch messages so that they are executed in the correct order. Facebook offers some properties to help one do just that such as `name` and `depends_on`. But this is not implemented in this library as far as I can see.

At the moment, the only way I can see to add the properties is to tack it onto the object returned by `sendRequest`.

What do you think?

Here's the relevant documentation
https://developers.facebook.com/docs/graph-api/making-multiple-requests#operations

**Comment by chentsulin** [comment]
Hi @ayoisaiah, thanks for the information of `name` and `depends_on` options. 

For now, we use https://github.com/Yoctol/messenger-batch to keep the order of our requests.

We will look into `name` and `depends_on` for the future underlying implementation.

**Comment by chentsulin** [comment]
Hi @ayoisaiah, We already add the support to specify dependencies between operations using  `name` and `depends_on`. See #501.

We will release this commit in v1.0 version in early October.
