### ISSUE TITLE
Is wechat usable?

### ISSUE THREAD

**Issue by beeing** [Yoctol/messaging-apis#357]
Hi, I see that the bottender does not have WeChat while this repo contains the API.

Does this means WeChat will be added soon?

**Comment by chentsulin** [comment]
Hi @beeing, we already have some experiments and ideas about potential WeChat API design in Bottender. It's in our plan, but we don't have a timeline for it.

**Comment by beeing** [comment]
Noted. Thanks for the update!

**Comment by chentsulin** [comment]
Address this issue at https://github.com/Yoctol/bottender/issues/393
