### ISSUE TITLE
IE11 support 

### ISSUE THREAD

**Issue by nidrax69** [Yoctol/messaging-apis#378]
In ie11, looks like there is an error in the Axios-error wrapper 

In line 4 of file index.js
`'use strict';function indent(str) {
  return str.
  split('\n').
  map(s => s ? `  ${s}` : '').
  join('\n');
}`

Are you supporting IE11 ?

Thanks

**Comment by chentsulin** [comment]
To support IE 11, we need to transform those two syntax :

- https://caniuse.com/#feat=template-literals
- https://caniuse.com/#feat=arrow-functions

**Comment by chentsulin** [comment]
We don't have a plan to support ie11 (it should be replaced by modern browser), so I am going to close this issue.
