### ISSUE TITLE
CORS Support for messaging-api-wechat

### ISSUE THREAD

**Issue by contrarianaupong** [Yoctol/messaging-apis#388]
HI,

I am having the No 'Access-Control-Allow-Origin' header is present on the requested resource. 

How to add the header in it?

Thank you

Here is the full error
Failed to load https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=xxxxxxxxxxx&secret=xxxxxxxxxxxx: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access.

**Comment by tw0517tw** [comment]
The header is controlled by WeChat server, we can't change that.

You should call these API on server side, not in browser.

**Comment by chentsulin** [comment]
As what @tw0517tw said, `messaging-api-wechat` is a package to run on node.js server, so you should never call ` https://api.weixin.qq.com/` using `messaging-api-wechat` in the browser.
