### ISSUE TITLE
Question about long polling

### ISSUE THREAD

**Issue by j0hnwhyte** [Yoctol/messaging-apis#389]
Hi
I've been using the library for some months, and my primary approach had always beed to poll every five seconds...

...which obviously is ridiculous for a chat bot, and after studying how the API works, I see that the documentation mentions that this library implements HTTP long polling.

How exactly should I make it work? It seems that all requests are one-shot and they're closed as soon as they are sent. Promises indeed can return only one time, as opposed to Observables. Did I get it wrong maybe? The documentation doesn't mention anything besides the fact that it exists.

Thanks a lot

**Comment by chentsulin** [comment]
Hi @j0hnwhyte,
long polling only be supported by telegram so I suppose you use it.

You can use `timeout` option:

> Timeout in seconds for long polling. Defaults to 0, i.e. usual short polling. Should be positive, short polling should be used for testing purposes only. 

https://core.telegram.org/bots/api#getupdates

For example:

```js
client.getUpdates({
  timeout: 5000, 
});
```

BTW, we have a high level framework - [Bottender](https://github.com/Yoctol/bottender) can do long polling with a better and managed way. It uses `messaging-api-telegram` under the hood.

Example:

```js
const { TelegramBot } = require('bottender');

const bot = new TelegramBot({
  accessToken: '__FILL_YOUR_TOKEN_HERE__',
});

bot.onEvent(async context => {
  await context.sendText('Hello World');
});

bot.createLongPollingRuntime({
  limit: 10, // Limits the number of updates to be retrieved. Defaults to 100.
  timeout: 60, // Timeout in seconds for long polling. Defaults to 0.
  allowed_updates: ['message', 'callback_query'], // List the types of updates you want your bot to receive
});
```

https://github.com/Yoctol/bottender/blob/master/examples/telegram-long-polling/index.js

**Comment by j0hnwhyte** [comment]
I saw bottender a few days ago, just late to the party because the app is already implemented. This is more than OK anyway, thanks for the answer, I'll try it out.

**Comment by j0hnwhyte** [comment]
One last thing, `client.getUpdates` works with promises, what is the correct way to retrieve multiple events?

**Comment by chentsulin** [comment]
`getUpdates` resolves up to 100 (max) events by default. You can pass `limit` option to customize it:

```js
const events = await client.getUpdates({
  timeout: 5000,
  limit: 100, // defualt: 100
});
```

**Comment by j0hnwhyte** [comment]
I'm sorry, I probably didn't express myself well enough. When you call a promise, the `.then()` method returns only once, therefore if an event comes before the timeout, it resolves the promise. But as promises can't be resolved more than once, this returns only one event per call..?

My tests seem to confirm this

**Comment by chentsulin** [comment]
You can use `while` loop to submit another `getUpdates` request after `getUpdates` request be resolved. 

See how we implement long polling mechanism in `TelegramBot.createLongPollingRuntime`:

https://github.com/Yoctol/bottender/blob/4a3c347c5c60a689f2e70acf7521f8b76bf0fd3f/src/bot/TelegramBot.js#L37-L70
