### ISSUE TITLE
[Messenger] Support 2018/9/27 Update

### ISSUE THREAD

**Issue by tw0517tw** [Yoctol/messaging-apis#398]
https://developers.facebook.com/docs/messenger-platform/changelog#2018---9---27--

- [Persona API (Beta)](https://developers.facebook.com/docs/messenger-platform/send-messages/personas/): This new API introduces the concept of "personas" to the Messenger Platform, which allows you to invoke different identities for your bot in-thread. When a persona is invoked, the user icon and display name for the bot is switched. The Page name continues to be shown in the header of the thread.
- [Message Tags](https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags): The BUSINESS_PRODUCTIVITY message tag is now available for sending non-promotional, business-related updates outside the 24+1 standard messaging window. The restriction on which templates may be sent using message tags has also been removed. Tagged messages may now use any template, as well as text.

**Comment by chentsulin** [comment]
```js
createPersona(person)
getPersona(personaId)
getPersonas(cursor)
deletePersona(personaId)
```

**Comment by tw0517tw** [comment]
Still have to check if tag is supported in all templated. Reopening.

> Tagged messages may now use any template, as well as text.

**Comment by tw0517tw** [comment]
Checked. It seems that we've already supported adding tags to different type of messages.
