### ISSUE TITLE
Get primitive message object

### ISSUE THREAD

**Issue by yusef-ho** [Yoctol/messaging-apis#411]
Hello, 
Is there any way i can get primitive type of object from Line.createxxxx()?
I would like to store the messages in sessions in order if user send something bot couldn't understand, bot can retrieve the last replied messages to send again.
Or is there any better way to achieve this?

Thanks~~~

**Comment by chentsulin** [comment]
Hi @yusef-ho,
You can just use `Line.createxxxx` APIs with the low-level `client.reply` or `client.push` to do what you want:

```js
client.reply(replyToken, [Line.createxxxx({ /* .. */ })]);
client.push(replyToken, [Line.createxxxx({ /* .. */ })]);
```

**Comment by chentsulin** [comment]
We don't have a plan to provide a core mechanism for storing last replies at this moment, so I'm going to close this for now.
