### ISSUE TITLE
Support Typetalk?

### ISSUE THREAD

**Issue by is2ei** [Yoctol/messaging-apis#429]
How about supporting [Typetalk](https://www.typetalk.com) ? If it's acceptable, I'd like to send PR.

**Comment by chentsulin** [comment]
Hi, we are currently don't have plan to support Typetalk officially, but It's still welcome to publish your package to community and add `messaging-apis` keyword on your `package.json`.

```json
{
  "keywords": [
    "messaging-apis"
  ],
}
```
