### ISSUE TITLE
How do I setup my webhook

### ISSUE THREAD

**Issue by Rotimi-Best** [Yoctol/messaging-apis#434]
I am stuck at the webhook url, need help

**Comment by maxml** [comment]
Telegram webhook isn't working: 

const { TelegramClient } = require('messaging-api-telegram');

const client = TelegramClient.connect('INPUT_YOUR_TOKEN');

client.setWebhook('https://INPUT_YOUR_ULR/webhook').then(x => {
    console.log(x);
    client.getWebhookInfo().then(info => {
        console.log(info);
        // {
        //   url: 'https://4a16faff.ngrok.io/',
        //   has_custom_certificate: false,
        //   pending_update_count: 0,
        //   max_connections: 40,
        // }
    });
});

var express = require('express')
var app = express()

app.get('/', function (req, res) {
    res.send('Hello World')
})
app.post('/webhook', function (req, res) {
    res.send('OK')
})

app.listen(8765)

Please, fix it

**Comment by Rotimi-Best** [comment]
Thanks, I wasn't indicating the right url.
