### ISSUE TITLE
[Viber] Public Account

### ISSUE THREAD

**Issue by nguyen991** [Yoctol/messaging-apis#440]
I don't know is it still possible to create an Public Account for Viber. This link https://www.viber.com/public-accounts not work anymore, and here https://twitter.com/ViberHelp/status/987012208071671809. Is there any replace solution

**Comment by chentsulin** [comment]
Hi @nguyen991, you may want to try this link:
https://partners.viber.com/login?returnUrl=%2Faccount%2Fcreate-bot-account

It should work.
