### ISSUE TITLE
[Messenger] GetUserProfile() default field options

### ISSUE THREAD

**Issue by aellanglet** [Yoctol/messaging-apis#441]
Hello !
First of all i love your work.

Actually i am using [bottender GetUserProfile context function](https://github.com/Yoctol/bottender/blob/master/src/context/MessengerContext.js#L154).

As i can see bottender is searching into [messaging-apis GetUserProfile function](https://github.com/Yoctol/messaging-apis/blob/master/packages/messaging-api-messenger/src/MessengerClient.js#L420) and by default it is requesting only for the basics fields.

Is it possible to add timezone, gender and locale as defaults fields too ?

Thanks !

**Comment by chentsulin** [comment]
Hi @aellanglet, we found that it's hard to make `timezone`, `gender` and `locale` included in default fields because you must to submit for permission to fetch them or you will get `(#100) Insufficient permission to access user profile` errors.

```json
{
  "error": {
    "message": "(#100) Insufficient permission to access user profile.",
    "type": "OAuthException",
    "code": 100,
    "error_subcode": 2018247,
    "fbtrace_id": "ANJbhbOoQWdbmhOeB8dUCrG"
  }
}
```

**Comment by chentsulin** [comment]
Let's keep tracking this in bottender repo: https://github.com/Yoctol/bottender/issues/395
