### ISSUE TITLE
npm audit says that module extend has vulnerability (path: messaging-api-messenger > append-query > extend)

### ISSUE THREAD

**Issue by rrakso** [Yoctol/messaging-apis#450]
![image](https://user-images.githubusercontent.com/23143274/61873031-28659300-aee5-11e9-8882-23dbfbb71bbd.png)

**Comment by rrakso** [comment]
I dunno if this is the place where i should post it 😅

**Comment by chentsulin** [comment]
Hi @rrakso,
This should be fixed after you update your `package-lock.json`.

https://stackoverflow.com/questions/50328324/how-do-i-fix-a-vulnerable-npm-package-in-my-package-lock-json-that-isnt-listed

Hope it helps. Correct me if I am wrong.

**Comment by rrakso** [comment]
Thanks!

wt., 27 sie 2019 o 05:42 C. T. Lin <notifications@github.com> napisał(a):
