### ISSUE TITLE
I keep getting an invalid parameter or an infinite loop

### ISSUE THREAD

**Issue by slidenerd** [Yoctol/messaging-apis#453]
Sorry, if this is a stupid question, how do subscribe the webhooks with your code
```js

const dotenv = require("dotenv");
dotenv.config({ path: ".env.dev" });


const express = require("express");
const Router = require("express").Router;
const router = new Router();
const app = express();
app.use(router);

router.get("/webhook", (req, res) => {
    const { MessengerClient } = require('messaging-api-messenger');

    const client = MessengerClient.connect({
        accessToken: process.env.FACEBOOK_PAGE_TOKEN,
        appId: process.env.FACEBOOK_APP_ID,
        appSecret: process.env.FACEBOOK_APP_SECRET,
        version: '4.0',
    });

    client.createSubscription({
        access_token: `${process.env.FACEBOOK_APP_ID}|${process.env.FACEBOOK_APP_SECRET}`,
        callback_url: 'http://localhost.com:3000/webhook',
        fields: ['messages', 'messaging_postbacks', 'messaging_referrals'],
        verify_token: process.env.FACEBOOK_VERIFY_TOKEN,
    });
});

app.listen(3000);

```

Keeps giving this error, I use ngrok http 3000 to tunnel localhost url, how do I verify the webhook in your library

**Comment by wtflink** [comment]
Hi @slidenerd, `createSubscription` is more like a one time thing, you create subscription once when you change your webhook endpoint, which in your case is when you restart your ngrok.
So as far as I can tell, you don't need it in your webhook handling flow.

**Comment by wtflink** [comment]
Also, I believe [facebook POST the webhook endpoint](https://developers.facebook.com/docs/graph-api/webhooks/getting-started) when they try to deliver the event to your server, so the router.get here:
`router.get("/webhook", (req, res) => { ...`
might not work as you think.

If you trying to build a chatbot, you should check out: https://github.com/Yoctol/bottender, which proudly made by us too!
