### ISSUE TITLE
no error message if connection failed

### ISSUE THREAD

**Issue by wangx6** [Yoctol/messaging-apis#541]

**Comment by wangx6** [comment]
It wud be greate if it could have `onConnect` function or return a promise for `connect`

**Comment by chentsulin** [comment]
Hi @wangx6, the `connect` static method is a factory method that creates a client instance using Axios HTTP client, but it doesn't establish any persistent connection actually under the hood. Sorry if the name of the method have confused you.

**Comment by chentsulin** [comment]
We're deprecating `connect` and embrace `new` keyword, so this naming issue is not a concern now.
