### ISSUE TITLE
various line related issues

### ISSUE THREAD

**Issue by xcelance** [Yoctol/messaging-apis#604]
Hello there,
I am trying to implement the api with node and react js, but I am facing some issues please help me with those listed below:

-- I am not able to send message to the client,
-- I want api to search the client from line chat by its id or name or by number so that i can message to the same.
-- List messages for particular user with which one is chatting.
And its all for the **web** application

**Comment by xcelance** [comment]
I am also struggling with the issue 
"Authentication failed due to the following reason: The access token malformed. Confirm that the access token in the authorization header is valid."

Please help me with these things.

**Comment by chentsulin** [comment]
Hi, please make sure you provide the correct access token to the `LineClient` class.

**Comment by xcelance** [comment]
@chentsulin I got that but i need proper api documentation for the issue I have created at the top, which is:

I am trying to implement the api with node and react js, but I am facing some issues please help me with those listed below:

-- I am not able to send message to the client,
-- I want api to search the client from line chat by its id or name or by number so that i can message to the same.
-- List messages for particular user with which one is chatting.
And its all for the web application


Please provide me solution for this one.

**Comment by xcelance** [comment]
is there anyone who can help me with my issues.

**Comment by chentsulin** [comment]
I'm afraid that this is not an issue related to `messaging-apis` libs. Here is for issue tracking and not a right place to ask this kind of question, so I'm going to close it.
