### ISSUE TITLE
[Messenger] version in npm don't sync with this version

### ISSUE THREAD

**Issue by Notekunn** [Yoctol/messaging-apis#610]
Enpoint me/messenger_profile change to me/custom_user_settings
Please update it

**Comment by Notekunn** [comment]
Please update on npm

**Comment by chentsulin** [comment]
What do you mean?
`me/messenger_profile` is still there and didn't change to `me/custom_user_settings`:
https://developers.facebook.com/docs/messenger-platform/reference/messenger-profile-api/

**Comment by Notekunn** [comment]
But set/get/delete PersistentMenu don't work with `me/messenger_profile`
It fixed by issue #579 but current version in npm don't update

**Comment by chentsulin** [comment]
Set/Get/Delete **Page Level** PersistentMenu do work with the `me/messenger_profile` endpoint. That PR isn't a fix. It's an entire new feature - Set/Get/Delete **User Level** PersistentMenu.

**Comment by Notekunn** [comment]
Thanks
