### ISSUE TITLE
[Messenger] How can I use getProfile results in batch Messages?

### ISSUE THREAD

**Issue by rbaks** [Yoctol/messaging-apis#611]
How Can I get and use the user's first name from batched request in message Batching?
`client.sendBatch([
  MessengerBatch.getUserProfile(USER_ID),
  MessengerBatch.sendText(USER_ID, 'Hello ${firstname}'),
]);`

**Comment by chentsulin** [comment]
Hi @rbaks 
This one would do the trick:

```js
client.sendBatch([ 
  MessengerBatch.getUserProfile(USER_ID, { name: 'profile' }), 
  MessengerBatch.sendText(USER_ID, 'Hello {result=profile:$.first_name}'), 
]);
```

**Comment by rbaks** [comment]
> Hi @rbaks
> This one would do the trick:
> 
> ```js
> client.sendBatch([ 
>   MessengerBatch.getUserProfile(USER_ID, { name: 'profile' }), 
>   MessengerBatch.sendText(USER_ID, 'Hello {result=profile:$.first_name}'), 
> ]);
> ```

It works but how can I assure that sendText waits on the results of getUserProfile before executing? Always in a single batch request

**Comment by chentsulin** [comment]
The order should be ensured by facebook.

> the server detects that the second operation depends on the first one, since the second operation references the result of the first one using JSONPath. The server executes a dependent operation only after the operation it depends on has finished executing.

See: https://developers.facebook.com/docs/graph-api/making-multiple-requests/?locale=en_US
