### ISSUE TITLE
support slack OAuth API

### ISSUE THREAD

**Issue by tw0517tw** [Yoctol/messaging-apis#62]
New package or use existing one?

**Comment by tw0517tw** [comment]
If we're making a new package for this, how should we name it? `messaging-api-slack-oauth`?
or rename the current one to `messaging-api-slack-webhook` and make the oauth one `messaging-api-slack`

**Comment by chentsulin** [comment]
we can have two clients in one messaging-api-slack package

**Comment by tw0517tw** [comment]
need document
