### ISSUE TITLE
[Telegram] Incorrect type of `updateId`

### ISSUE THREAD

**Issue by sigorilla** [Yoctol/messaging-apis#622]
There is incorrect type for [`updateId`](https://github.com/Yoctol/messaging-apis/blob/master/packages/messaging-api-telegram/src/TelegramTypes.ts#L10) in type `Update`, it should be `number`.

Prof: https://core.telegram.org/bots/api#update

**Comment by chentsulin** [comment]
This has been fixed by https://github.com/Yoctol/messaging-apis/pull/623.
