### ISSUE TITLE
get contacts in messaging-api-telegram

### ISSUE THREAD

**Issue by nguyenthanhtruongntt85** [Yoctol/messaging-apis#646]
how to get contacts in module messaging-api-telegram?
 I see api have get contacst: https://core.telegram.org/method/contacts.getContacts
Thanks

**Comment by chentsulin** [comment]
Hi @nguyenthanhtruongntt85, unfortunately `contacts.getContacts` is not part of [Telegram Bot API](https://core.telegram.org/bots/api#available-methods), so we are not gonna support it in  `messaging-api-telegram`.

To use it, you must learn how to execute [tdlib/td](https://github.com/tdlib/td) C functions in your Nodejs environment.
This [Stackoverflow question](https://stackoverflow.com/questions/51900357/how-to-use-telegrams-tdlib-with-node-js) may help.
