### ISSUE TITLE
[Viber] An issue with creating Keyboard

### ISSUE THREAD

**Issue by RostyslavRadysh** [Yoctol/messaging-apis#652]
Hi! :)
First of all, thank you for the library. You are wonderful. But I have an issue with creating Keyboard (

If I use Keyboard for Viber I get the following error:
`2021-08-31T19:05:31.023 [Error] Viber API - keyboard is not valid. [object has missing required properties (["Type"])]
`![image](https://user-images.githubusercontent.com/29781922/131562633-b7665beb-78f1-4930-83dd-ce2de081160a.png)

My code:
![image](https://user-images.githubusercontent.com/29781922/131562766-d66690e7-0d97-4aac-90bc-5749675471cb.png)

As far as I see the request has to have a Type:
![image](https://user-images.githubusercontent.com/29781922/131563653-62d435e7-89ba-48fc-9683-26447a176840.png)

Maybe someone knows how to add a Type or fix it?

**Comment by chentsulin** [comment]
How about adding `type: 'keyboard'` to the request, would this work?

```js
await this.client.sendText(key, message, {
  keyboard: {
    type: 'keyboard',
    defaultHeight: true,
    bgColor: '#FFFFFF',
    buttons: [
      {
        columns: 6,
        rows: 1,
        bgColor: '#2db9b9',
        bgMediaType: 'gif',
        bgMedia: 'http://www.url.by/test.gif',
        bgLoop: true,
        actionType: 'open-url',
        actionBody: 'www.tut.by',
        image: 'www.tut.by/img.jpg',
        text: 'Key text',
        textVAlign: 'middle',
        textHAlign: 'center',
        textOpacity: 60,
        textSize: 'regular',
      },
    ],
  },
});
```

**Comment by RostyslavRadysh** [comment]
It doesn't work because of Typescript (
![image](https://user-images.githubusercontent.com/29781922/131740130-ca1eea9e-ffb4-4627-af46-fa48e37139fd.png)

But I believe if we add 'type' to Keyboard it will work. Maybe can you update the package?
![image](https://user-images.githubusercontent.com/29781922/131740330-b2fbd95d-d523-4d82-811c-dab522720c79.png)

**Comment by chentsulin** [comment]
@RostyslavRadysh I released a fix on that. See if your type works fine in 1.0.6:

https://github.com/Yoctol/messaging-apis/releases/tag/v1.0.6

**Comment by RostyslavRadysh** [comment]
It works, thank you :)
![image](https://user-images.githubusercontent.com/29781922/131906400-a339dd59-3ded-46bf-8376-306e05a7c68a.png)
